### ISSUE TITLE
Installing on AWS RDS

### ISSUE THREAD

**Issue by krupt** [ancoron/pg-uuid-v1#1]
Hi there. Thank you for that extension. It's really good to build a great product/system.
Do you know how to install it on an AWS RDS PostgreSQL instance?
Thanks.

**Comment by krupt** [comment]
Also, do you know how to add this extension to some docker image of PostgreSQL?
Thank you.

**Comment by ancoron** [comment]
Sorry for the late reply.

AWS does not allow to add arbitrary extensions. They compile them for their systems and they only have a fixed list which they support / are available for installation.

This - of course - is a big downside of AWS, but almost any managed PostgreSQL service.

For running your own with Docker, I have created an [`example.Dockerfile`](example.Dockerfile) which you should be able to use.
